/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ImageCard: typeof import('./../components/ImageCard.vue')['default']
    Logo: typeof import('./../components/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./../components/SideNav.vue')['default']
    SideNavButton: typeof import('./../components/SideNavButton.vue')['default']
  }
}
